apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx

  rules:
  - host: books.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: books-service
            port:
              number: 80

  - host: travel.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: travel-service
            port:
              number: 80

  - host: cars.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cars-service
            port:
              number: 80

  - host: temple.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: temple-service
            port:
              number: 80

  - host: bike.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bike-service
            port:
              number: 80
