apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - app: books
      - app: travel
      - app: cars
      - app: temple
      - app: bike

  template:
    metadata:
      name: '{{app}}'
    spec:
      project: default

      source:
        repoURL: https://github.com/YOUR_GITHUB/gitops-multi-app-demo
        targetRevision: HEAD
        path: k8s-manifests/{{app}}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{app}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
