apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-app
  namespace: travel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel
  template:
    metadata:
      labels:
        app: travel
    spec:
      containers:
      - name: travel
        image: yourdockerhub/travel:v1
        ports:
        - containerPort: 5000
