apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-app
  namespace: cars
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cars
  template:
    metadata:
      labels:
        app: cars
    spec:
      containers:
      - name: cars
        image: yourdockerhub/cars:v1
        ports:
        - containerPort: 5000
