name: Build and Push All Apps to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'apps/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [books, travel, cars, temple, bike]

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build Docker Image
      run: |
        docker build -t ${{ matrix.app }} ./apps/${{ matrix.app }}

    - name: Tag Docker Image
      run: |
        docker tag ${{ matrix.app }}:latest 426192960096.dkr.ecr.us-east-1.amazonaws.com/${{ matrix.app }}:latest

    - name: Push Docker Image
      run: |
        docker push 426192960096.dkr.ecr.us-east-1.amazonaws.com/${{ matrix.app }}:latest
